version: '3'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dataset
      POSTGRES_USER: miniproject
      POSTGRES_PASSWORD: myminiproject
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
