name: 'my_project'
version: '1.0.0'
config-version: 2

profile: 'my_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_project:
    staging:
      +schema: _staging
      +database: dataset

    intermediate:
      +materialized: table
      +schema: _intermediate
      +database: dataset

    mart:
      +materialized: table
      +schema: mart
      +database: dataset
