version: 2

source:
  - name: raw
    database: dataset
    schema: public

    tables:
      - name: customers
        columns:
          - name: customerkey
            description: "unique identifier for each customer"
            tests:
              - unique
              - not_null
      
      - name: sales
        columns:
          - name:
      
      - name: stores
        columns:
          - name: storekey
            description: "unique identifier for each store"
            tests:
              - unique
              - not_null
      
      - name: products
        columns:
          - name: productkey
            description: "unique identifier for each product"
            tests:
              - unique
              - not_null
      
      - name: data_dictionary
        description: "information for each column from every table"

      - name: exchange_rates
        description: "information for currency exchange"