my_project:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: miniproject
      pass: myminiproject
      dbname: dataset
      schema: public

  target: dev
